// Spike 1: verify Vrm10.LoadPathAsync + ImmediateCaller runs synchronously
// in EditMode and produces a Vrm10Instance with a SkinnedMeshRenderer.
// Spike-only — deleted after Task 11 (subsumed by production code).
// Task 28: canLoadVrm0X flipped to true so the test exercises VRM 0.x as well.

using NUnit.Framework;
using UniGLTF;
using UnityEngine;
using UniVRM10;

namespace Conformance.Tests
{
    public class Vrm10LoadSpike
    {
        // Path generated by `vrm-asset-generator emit-default` in the plan's Step 4.2.
        private const string FixturePath = "/tmp/univrm-spike/spike1_mtoon_default.vrm";

        [Test]
        public void LoadProducesVrm10InstanceWithSkinnedMesh()
        {
            if (!System.IO.File.Exists(FixturePath))
            {
                Assert.Ignore($"fixture not present at {FixturePath}; generate via emit-default");
            }

            var task = Vrm10.LoadPathAsync(
                FixturePath,
                canLoadVrm0X: true,
                showMeshes: true,
                awaitCaller: new ImmediateCaller(),
                ct: System.Threading.CancellationToken.None);

            // ImmediateCaller runs awaits synchronously; the task should
            // be completed by the time LoadPathAsync returns its Task.
            Assert.IsTrue(task.IsCompleted, "task should be synchronously complete under ImmediateCaller");
            Assert.AreEqual(System.Threading.Tasks.TaskStatus.RanToCompletion, task.Status);

            var instance = task.Result;
            Assert.IsNotNull(instance, "Vrm10Instance must not be null");

            // Accept either SkinnedMeshRenderer (typical for humanoid VRMs) or
            // MeshRenderer (our parametric test asset generator currently emits
            // an unskinned sphere). Either way, asserts the load surfaced a
            // renderable mesh.
            var renderer = instance.GetComponentInChildren<Renderer>();
            Assert.IsNotNull(renderer, "loaded VRM must have at least one Renderer (SkinnedMesh or Mesh)");
            var mf = renderer.GetComponent<MeshFilter>();
            var smr = renderer as SkinnedMeshRenderer;
            var mesh = smr != null ? smr.sharedMesh : (mf != null ? mf.sharedMesh : null);
            Assert.IsNotNull(mesh, "renderer must reference a mesh");
            Assert.Greater(mesh.vertexCount, 0);

            Object.DestroyImmediate(instance.gameObject);
        }
    }
}
