// L3: real per-test rendering through UniVRM v0.131.0 + Built-in RP.
// Phase 1 ops (load_vrm, set_camera, set_lighting, set_post_processing,
// render) are implemented. Phase 2 (spring-bone physics) deferred to L4 —
// spring-bone tests render in rest pose at L3.
//
// Invoked from launcher.sh as:
//   Unity -batchmode -projectPath ... -executeMethod Conformance.RunBatch -- manifest.json results.ndjson
//
// The `--` separator routes everything after it into
// `Environment.GetCommandLineArgs()` as plain strings (Unity passes
// everything past `--` through unmodified).

// VRMA (VRMC_vrm_animation): RunBatch does not currently handle test
// plans that reference a .vrma. UniVRM is the consortium reference for
// VRMA and will be wired in via VrmAnimationImporter at vrma-phase4 of
// the VRMA implementation plan. Until then, VRMA test plans will be
// generated by phase 3 of the VRMA plan but UniVRM's batch will not
// process them; the runner-side handling for that case lands in
// vrma-phase2 (runner integration).
//
// render_sequence (multi-frame capture, RFC-0004): same shape as VRMA.
// UniVRM is the consortium reference; full impl is bundled with the
// deferred L4-PlayMode follow-up (FastSpringBone gates on
// Application.isPlaying, so the per-frame loop needs PlayMode anyway).
// Detect-and-error for test plans declaring a `render_sequence:` block
// lands alongside the test-plan schema change in render-sequence
// phase 4. The phase-1 op surface (Rust types, methodology pins) is
// complete on the runner side; UniVRM has no per-op stub to add.
//
// Unlike VMK/three-vrm/godot-vrm, UniVRM has no per-op JSON-RPC
// dispatcher to stub — RunBatch is a batched filesystem contract per
// RFC-0003. This is why there's no Unimplemented stub here.

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UniGLTF;
using UnityEditor;
using UnityEngine;
using UniVRM10;

// Task 28: source_spec_version detection helper — shared by EditMode
// (Conformance.RunBatch) and PlayMode (BatchRunner). Reads the GLB JSON
// chunk directly so that the original extensionsUsed is inspected before
// UniVRM's auto-migration to VRM 1.0 internal representation.
// Placed here (Conformance.cs) rather than Manifest.cs to keep Manifest.cs
// as a pure DTO file.
namespace Conformance
{
    // public (not internal): called from the PlayMode batch runner
    // (Conformance.Tests.Play) and EditMode tests (Conformance.Tests), which
    // live in separate assemblies — internal is invisible across the asmdef
    // boundary (CS0122).
    public static class SpecVersionDetector
    {
        /// <summary>
        /// Read the first JSON chunk of a GLB file and return "0.x" if the
        /// asset declares the "VRM" extension (VRM 0.x), or "1.0" if it
        /// declares "VRMC_vrm" (VRM 1.0).
        ///
        /// Returns null on any parse failure so callers can treat it as
        /// "unknown" rather than crashing the whole batch.
        /// </summary>
        public static string DetectFromGlbPath(string path)
        {
            try
            {
                // GLB layout (little-endian):
                //   [0-3]  magic        0x46546C67 "glTF"
                //   [4-7]  version      u32
                //   [8-11] length       u32
                //   [12-15] chunk0Len   u32
                //   [16-19] chunk0Type  u32  (0x4E4F534A = "JSON")
                //   [20..20+chunk0Len]  UTF-8 JSON text
                //
                // We only read the JSON chunk; no need to load the whole file.
                using var fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
                using var br = new BinaryReader(fs, Encoding.UTF8, leaveOpen: true);

                var magic = br.ReadUInt32();
                if (magic != 0x46546C67) return null; // not GLB

                br.ReadUInt32(); // version
                br.ReadUInt32(); // total length

                var chunkLen  = br.ReadUInt32();
                var chunkType = br.ReadUInt32();
                if (chunkType != 0x4E4F534A) return null; // chunk 0 is not JSON

                var jsonBytes = br.ReadBytes((int)chunkLen);
                var json = Encoding.UTF8.GetString(jsonBytes);

                // Lightweight check: look for the extension name strings without
                // a full JSON parse. Both names are unique enough that a simple
                // contains check is reliable for well-formed GLB files.
                if (json.Contains("\"VRMC_vrm\"")) return "1.0";
                if (json.Contains("\"VRM\""))      return "0.x";
                return null;
            }
            catch
            {
                return null;
            }
        }
    }
}

namespace Conformance
{
    public static class Conformance
    {
        public static void RunBatch()
        {
            try
            {
                var args = ExtractAdapterArgs();
                if (args.Count < 2)
                {
                    Debug.LogError(
                        $"Conformance.RunBatch: expected 2 args (manifest, results); got {args.Count}");
                    EditorApplication.Exit(2);
                    return;
                }
                var manifestPath = args[0];
                var resultsPath = args[1];

                var manifestJson = File.ReadAllText(manifestPath);
                var manifest = JsonUtility.FromJson<Manifest.ManifestDto>(manifestJson);
                if (manifest == null || manifest.tests == null)
                {
                    Debug.LogError($"Conformance.RunBatch: failed to parse manifest at {manifestPath}");
                    EditorApplication.Exit(3);
                    return;
                }

                using var stream = new FileStream(
                    resultsPath, FileMode.Create, FileAccess.Write, FileShare.Read);

                // _meta envelope (line 1).
                var meta = new Manifest.MetaDto
                {
                    _meta = true,
                    manifest_version = manifest.manifest_version,
                    renderer_name = manifest.renderer_name,
                    renderer_version = "v0.131.0",
                    unity_version = Application.unityVersion,
                    render_pipeline = "Built-in RP",
                    total_tests = manifest.tests.Length,
                };
                WriteLine(stream, JsonUtility.ToJson(meta));

                foreach (var t in manifest.tests)
                {
                    var entry = RenderOne(manifest.output_dir, t);
                    WriteLine(stream, JsonUtility.ToJson(entry));
                }

                EditorApplication.Exit(0);
            }
            catch (Exception e)
            {
                Debug.LogError($"Conformance.RunBatch: unhandled exception: {e}");
                EditorApplication.Exit(1);
            }
        }

        // Render one test. Returns the EntryDto to append to the NDJSON.
        // Per-test failures produce a status="error" entry; they never
        // throw out of this method (batch must continue).
        private static Manifest.EntryDto RenderOne(string outputDir, Manifest.TestEntryDto t)
        {
            // Pre-flight reject of unsupported post-processing.
            try
            {
                SceneSetup.AssertPostProcessingSupported(t.post_processing);
            }
            catch (SceneSetup.UnsupportedFeatureException ex)
            {
                return new Manifest.EntryDto
                {
                    test_id = t.test_id,
                    status = "error",
                    error = new Manifest.ErrorDto
                    {
                        code = -32602,
                        message = $"unsupported {ex.Feature}: {ex.Value}",
                        data = new Manifest.ErrorDataDto
                        {
                            feature = ex.Feature,
                            value = ex.Value,
                            supported = ex.Supported,
                        },
                    },
                };
            }

            // VRMA tests require PlayMode (AnimationClipPlayable graphs).
            // EditMode batch path rejects them explicitly so failures surface as
            // "feature: vrma" rather than silent rest-pose renders.
            // PlayMode batch (Conformance.Tests.Play.BatchRunner) handles the real
            // VRMA application path (phase 4 task 8).
            if (t.animation != null && t.animation.vrma != null)
            {
                return new Manifest.EntryDto
                {
                    test_id = t.test_id,
                    status = "error",
                    error = new Manifest.ErrorDto
                    {
                        code = -32000,
                        message = "VRMA tests require PlayMode batch (animation.vrma present)",
                        data = new Manifest.ErrorDataDto
                        {
                            feature = "vrma",
                            value = t.animation.vrma.path,
                            supported = new[] { "RUN_UNIVRM_PLAYMODE=1 with Conformance.Tests.Play.BatchRunner" },
                        },
                    },
                };
            }

            // render_sequence tests require PlayMode batch — they need the per-
            // frame physics + render loop that's only available with
            // Application.isPlaying == true. EditMode -executeMethod has no
            // frame ticks. Mirror the VRMA rejection above.
            //
            // JsonUtility quirk: absent JSON sub-objects deserialize as
            // default-constructed instances (frame_count=0), so a non-null
            // check alone matches every static-frame plan too. Guard on the
            // payload-bearing frame_count to match BatchRunner.cs.
            if (t.render_sequence != null && t.render_sequence.frame_count > 0)
            {
                return new Manifest.EntryDto
                {
                    test_id = t.test_id,
                    status = "error",
                    error = new Manifest.ErrorDto
                    {
                        code = -32000,
                        message = "render_sequence tests require PlayMode batch",
                        data = new Manifest.ErrorDataDto
                        {
                            feature = "render_sequence",
                            value = $"frame_count={t.render_sequence.frame_count}",
                            supported = new[] { "default PlayMode launcher (omit L3_EDITMODE)" },
                        },
                    },
                };
            }

            // Task 28: detect source spec version from the GLB JSON chunk
            // before UniVRM migrates 0.x → 1.0 internally. Null = unknown
            // (parse failure); the field is omitted from the result entry on
            // error paths where load didn't complete.
            var sourceSpecVersion = SpecVersionDetector.DetectFromGlbPath(t.vrm_path);

            GameObject vrmGo = null;
            GameObject lightGo = null;
            GameObject cameraGo = null;
            try
            {
                // Load. canLoadVrm0X: true so that VRM 0.x assets are accepted
                // and auto-migrated to 1.0 internal representation (Task 28).
                var loadTask = Vrm10.LoadPathAsync(
                    t.vrm_path,
                    canLoadVrm0X: true,
                    showMeshes: true,
                    awaitCaller: new ImmediateCaller(),
                    ct: System.Threading.CancellationToken.None);
                if (!loadTask.IsCompletedSuccessfully)
                {
                    return ErrorEntry(t.test_id, -32001, "LoadFailed", "L3", loadTask.Exception?.ToString());
                }
                var vrm = loadTask.Result;
                vrmGo = vrm.gameObject;

                // L4: disable auto-update so spring-bone stepping is
                // deterministic and entirely driver-owned.
                PhysicsDriver.DisableAutoUpdate(vrm);

                // Camera + Light objects.
                cameraGo = new GameObject("Camera");
                var cam = cameraGo.AddComponent<Camera>();
                SceneSetup.ConfigureCamera(cam, t.camera);

                lightGo = new GameObject("Directional");
                var light = lightGo.AddComponent<Light>();
                SceneSetup.ConfigureLighting(light, t.lighting);

                // L4: spring-bone physics — settle from rest pose, then
                // optionally animate root transform while stepping
                // spring-bone. Both are no-ops when the corresponding DTO
                // field is null (Phase 1 MToon tests).
                PhysicsDriver.Settle(vrm, t.physics);
                PhysicsDriver.AnimateRootTransform(vrm, t.animation);

                // Capture.
                var outputPath = Path.Combine(outputDir, t.test_id + ".png");
                var captureResult = Capture.Render(cam, t.output, outputPath);

                return new Manifest.EntryDto
                {
                    test_id = t.test_id,
                    status = "ok",
                    output_path = captureResult.outputPath,
                    actual_color_space = captureResult.actualColorSpace,
                    render_seconds = captureResult.renderSeconds,
                    source_spec_version = sourceSpecVersion,
                };
            }
            catch (Exception e)
            {
                return ErrorEntry(t.test_id, -32002, "RenderFailed", "L3", e.ToString());
            }
            finally
            {
                if (cameraGo != null) UnityEngine.Object.DestroyImmediate(cameraGo);
                if (lightGo != null) UnityEngine.Object.DestroyImmediate(lightGo);
                if (vrmGo != null) UnityEngine.Object.DestroyImmediate(vrmGo);
            }
        }

        private static Manifest.EntryDto ErrorEntry(string test_id, int code, string label, string phase, string detail)
        {
            const int max = 1000;
            if (detail != null && detail.Length > max) detail = detail.Substring(0, max) + "…";
            return new Manifest.EntryDto
            {
                test_id = test_id,
                status = "error",
                error = new Manifest.ErrorDto
                {
                    code = code,
                    message = $"{label}: {detail ?? "no detail"}",
                    data = new Manifest.ErrorDataDto { phase = phase },
                },
            };
        }

        private static List<string> ExtractAdapterArgs()
        {
            var args = Environment.GetCommandLineArgs();
            var result = new List<string>();
            var capture = false;
            foreach (var a in args)
            {
                if (capture)
                {
                    result.Add(a);
                }
                else if (a == "--")
                {
                    capture = true;
                }
            }
            return result;
        }

        private static void WriteLine(FileStream stream, string json)
        {
            var bytes = Encoding.UTF8.GetBytes(json + "\n");
            stream.Write(bytes, 0, bytes.Length);
            stream.Flush(flushToDisk: true);
        }
    }
}
