#!/usr/bin/env bash
#
# Installs the mrxz/vrm-validator npm library + a small Node CLI shim into
# ./.tools/ so the Rust validator wrapper can invoke it as a subprocess.
#
# We use the npm package (vrm-validator) rather than a pre-built native
# binary because the upstream project does not currently publish native
# release artifacts (see https://github.com/mrxz/vrm-validator/releases).
# Dart-from-source is the alternative; it requires installing the Dart
# SDK on every dev machine and CI runner. Node is universally available
# already, so we trade ~50ms of startup overhead per validation for zero
# extra build prerequisites.

set -euo pipefail

# Pinned vrm-validator npm version. Bumping requires regenerating the
# golden corpus, since validator semantics may shift.
VALIDATOR_VERSION="${VRM_VALIDATOR_VERSION:-2.0.0-dev.3.10}"

INSTALL_DIR="${INSTALL_DIR:-$(pwd)/.tools/vrm-validator}"

mkdir -p "${INSTALL_DIR}"

if ! command -v node >/dev/null 2>&1; then
    echo "error: node is required but not on PATH" >&2
    exit 1
fi
if ! command -v npm >/dev/null 2>&1; then
    echo "error: npm is required but not on PATH" >&2
    exit 1
fi

cd "${INSTALL_DIR}"

if [ ! -f package.json ]; then
    cat > package.json <<EOF
{
  "name": "vrm-conformance-validator-shim",
  "version": "0.0.0",
  "private": true,
  "description": "Auto-generated by scripts/install-validator.sh"
}
EOF
fi

echo "Installing vrm-validator@${VALIDATOR_VERSION} into ${INSTALL_DIR}"
npm install --no-audit --no-fund --silent "vrm-validator@${VALIDATOR_VERSION}"

# Drop the CLI shim. It reads a file path from argv[2], runs validateBytes,
# prints the JSON report to stdout, and exits non-zero on any error issue.
cat > cli.js <<'EOF'
#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const validator = require('vrm-validator');

async function main() {
    const inputPath = process.argv[2];
    if (!inputPath) {
        process.stderr.write('usage: cli.js <path-to-vrm>\n');
        process.exit(2);
    }
    if (!fs.existsSync(inputPath)) {
        process.stderr.write(`error: file not found: ${inputPath}\n`);
        process.exit(2);
    }

    const bytes = fs.readFileSync(inputPath);
    const report = await validator.validateBytes(new Uint8Array(bytes), {
        uri: path.basename(inputPath),
        maxIssues: 0, // unlimited
    });

    process.stdout.write(JSON.stringify(report));

    const numErrors = (report.issues && report.issues.numErrors) || 0;
    process.exit(numErrors > 0 ? 1 : 0);
}

main().catch((err) => {
    process.stderr.write(`validator threw: ${err.stack || err}\n`);
    process.exit(3);
});
EOF
chmod +x cli.js

# Convenience launcher at .tools/vrm-validator-cli — the Rust wrapper looks here.
cat > "$(dirname "${INSTALL_DIR}")/vrm-validator-cli" <<EOF
#!/usr/bin/env bash
exec node "${INSTALL_DIR}/cli.js" "\$@"
EOF
chmod +x "$(dirname "${INSTALL_DIR}")/vrm-validator-cli"

echo "Installed:"
echo "  CLI wrapper: $(dirname "${INSTALL_DIR}")/vrm-validator-cli"
echo "  Library:     ${INSTALL_DIR}/node_modules/vrm-validator"

# Self-test: print supported extensions to confirm the library loaded.
node -e "const v=require('${INSTALL_DIR}/node_modules/vrm-validator'); console.error('vrm-validator version:', v.version()); console.error('supported extensions:', v.supportedExtensions().length);"
